version: '3.1'

services:

  jupyter:
    image: jupyter/minimal-notebook
    restart: always
    ports:
      - 8888:8888
    user: root
    environment:
      - NB_UID=$HOST_UID
      - NB_GID=$HOST_GID
    volumes:
      - ./:/home/jovyan/work
    command: ["start.sh", "jupyter", "lab", "--NotebookApp.token=''"]

